### ISSUE TITLE
rf.checkForPacket does not detect packets from other remote controls

### ISSUE THREAD

**Issue by thomasvnl** [supersjimmie/IthoEcoFanRFT#2]
The title is pretty explanatory, but to elaborate: I don't see the example code in this repository respond to packets send by other Itho remotes. I was hoping that it would, because that would mean I could check the current "override" state if a user wants to override the system via the original remote control. 

Does anyone experience this same issue? Any suggestions on where to start looking to solve it on my side?

**Comment by supersjimmie** [comment]
Sorry for the late response... Could you please try the latest git version, that I uploaded yesterday?

**Comment by thomasvnl** [comment]
I will next week. Great timing, my vacation just started 😁! Will let you
know, thanks for the heads up.

**Comment by thomasvnl** [comment]
Can't get it to work, unfortunately. Using the default ino file included, and wiring up GDO2 of the CC1101 to D2 of the ESP8266 does not seem to result in picking up commands sent from a nearby remote. I've seen on tweakers that others have had success with your code so I have ordered new CC1101 modules to be able to test for hardware failure.

**Comment by pascalsaul** [comment]
I've the same issue... Can't imagine it's the hardware since sending is OK and sometimes I receive some input from devices in the neigborhood I guess... Everything except my own devices...

**Comment by thomasvnl** [comment]
@pascalsaul Ik think it has to do with different versions of Itho fans out there. Some use a different protocol. As I understood from the topic here (where supersjimmie is also a member): https://gathering.tweakers.net/forum/list_messages/1690945 the latest version seems to only work for newer Itho ECO RFT fans. This house is outfitted with an ECO FAN-2 which is probably an older model (rental house, nothing to do about that). Using the older version of the code I am able to control the fan but not see incoming messages. The newer version of the code didn't even allow me to control the fan anymore.

**Comment by pascalsaul** [comment]
The [CVE ECO RFT HE](https://www.ithodaalderop.nl/sites/default/files/documents/handleiding_cve_eco_rft.pdf) I placed here is from 2013 so quite 'new'. I'm able to control the unit with all versions out there as far as I tested. I try to debug the receiving part of it with all kinds of .ino files out there now. Hopefully someone can point us in the right direction why it is failing.

**Comment by thomasvnl** [comment]
At least you've had more luck with the code than I did. Hopefully you'll get to receive stuff too!

**Comment by pascalsaul** [comment]
I could create the fix with this [information](https://github.com/supersjimmie/IthoEcoFanRFT/pull/1)

**Comment by supersjimmie** [comment]
Additions and Fix implemented.
